import { Injectable } from '@angular/core';
import { Observable, interval } from 'rxjs';
import { map, take } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class MockStreamingService {
  private mockData = [
    { role: "assistant", content: null },
    { role: null, content: "" },
    { role: null, content: "U" },
    { role: null, content: " kunt" },
    { role: null, content: " renov" },
    { role: null, content: "at" },
    { role: null, content: "iew" },
    { role: null, content: "erken" },
    { role: null, content: " die" },
    { role: null, content: " na" },
    { role: null, content: " de" },
    { role: null, content: " op" },
    { role: null, content: "maak" },
    { role: null, content: " van" },
    { role: null, content: " uw" },
    { role: null, content: " energie" },
    { role: null, content: "prest" },
    { role: null, content: "atie" },
    { role: null, content: "cert" },
    { role: null, content: "ific" },
    { role: null, content: "aat" },
    { role: null, content: " (" },
    { role: null, content: "E" },
    { role: null, content: "PC" },
    { role: null, content: ")" },
    { role: null, content: " zijn" },
    { role: null, content: " uitgevoerd" },
    { role: null, content: " zelf" },
    { role: null, content: " toevoegen" },
    { role: null, content: " aan" },
    { role: null, content: " uw" },
    { role: null, content: " woning" },
    { role: null, content: "pas" },
    { role: null, content: " via" },
    { role: null, content: " '" },
    { role: null, content: "uw" },
    { role: null, content: " energet" },
    { role: null, content: "ische" },
    { role: null, content: " renov" },
    { role: null, content: "at" },
    { role: null, content: 'iew' },
    { role: null, content: 'erken' },
    { role: null, content: "'" },
    { role: null, content: '.' },
    { role: null, content: ' Deze' },
    { role: null, content: ' werken' },
    { role: null, content: ' komen' },
    { role: null, content: ' dan' },
    { role: null, content: ' op' },
    { role: null, content: ' een' },
    { role: null, content: ' tijd' },
    { role: null, content: 'sl' },
    { role: null, content: 'ijn' },
    { role: null, content: ' in' },
    { role: null, content: ' uw' },
    { role: null, content: ' woning' },
    { role: null, content: 'pas' },
    { role: null, content: ' te' },
    { role: null, content: ' staan' },
    { role: null, content: '.' },
    { role: null, content: ' U' },
    { role: null, content: ' kunt' },
    { role: null, content: ' voorlopig' },
    { role: null, content: ' enkel' },
    { role: null, content: ' energet' },
    { role: null, content: 'ische' },
    { role: null, content: ' renov' },
    { role: null, content: 'at' },
    { role: null, content: 'iew' },
    { role: null, content: 'erken' },
    { role: null, content: ' opl' },
    { role: null, content: 'aden' },
    { role: null, content: ',' },
    { role: null, content: ' zoals' },
    { role: null, content: ':\n\n' },
    { role: null, content: '-' },
    { role: null, content: ' Is' },
    { role: null, content: 'olat' },
    { role: null, content: 'iew' },
    { role: null, content: 'erken' },
    { role: null, content: ' aan' },
    { role: null, content: ' het' },
    { role: null, content: ' dak' },
    { role: null, content: ',' },
    { role: null, content: ' vloer' },
    { role: null, content: ' of' },
    { role: null, content: ' muur' },
    { role: null, content: '\n' },
    { role: null, content: '-' },
    { role: null, content: ' Pla' },
    { role: null, content: 'atsen' },
    { role: null, content: ' van' },
    { role: null, content: ' nieuwe' },
    { role: null, content: ' ven' },
    { role: null, content: 'sters' },
    { role: null, content: '\n' },
    { role: null, content: '-' },
    { role: null, content: ' Vern' },
    { role: null, content: 'ieu' },
    { role: null, content: 'wing' },
    { role: null, content: ' van' },
    { role: null, content: ' de' },
    { role: null, content: ' verwarm' },
    { role: null, content: 'ings' },
    { role: null, content: 'install' },
    { role: null, content: 'atie' },
    { role: null, content: '\n' },
    { role: null, content: '-' },
    { role: null, content: ' Pla' },
    { role: null, content: 'atsen' },
    { role: null, content: ' van' },
    { role: null, content: ' zonnepanelen' },
    { role: null, content: ' of' },
    { role: null, content: ' zonne' },
    { role: null, content: 'bo' },
    { role: null, content: 'iler' },
    { role: null, content: '\n' },
    { role: null, content: '-' },
    { role: null, content: ' Pla' },
    { role: null, content: 'atsen' },
    { role: null, content: ' van' },
    { role: null, content: ' een' },
    { role: null, content: ' ventil' },
    { role: null, content: 'aties' },
    { role: null, content: 'ysteem' },
    { role: null, content: '\n\n' },
    { role: null, content: 'Voor' },
    { role: null, content: ' elk' },
    { role: null, content: ' uitgevoerd' },
    { role: null, content: ' renov' },
    { role: null, content: 'at' },
    { role: null, content: 'iew' },
    { role: null, content: 'erk' },
    { role: null, content: ' kunt' },
    { role: null, content: ' u' },
    { role: null, content: ' een' },
    { role: null, content: ' aantal' },
    { role: null, content: ' gegevens' },
    { role: null, content: ' invo' },
    { role: null, content: 'eren' },
    { role: null, content: ' in' },
    { role: null, content: ' uw' },
    { role: null, content: ' woning' },
    { role: null, content: 'pas' },
    { role: null, content: ' en' },
    { role: null, content: ',' },
    { role: null, content: ' als' },
    { role: null, content: ' u' },
    { role: null, content: ' dit' },
    { role: null, content: ' wen' },
    { role: null, content: 'st' },
    { role: null, content: ',' },
    { role: null, content: ' ook' },
    { role: null, content: ' bewijs' },
    { role: null, content: 'stukken' },
    { role: null, content: ' toevoegen' },
    { role: null, content: '.' },
    // { role: null, content: ' Dit' },
    // { role: null, content: ' laatste' },
    // { role: null, content: ' is' },
    // { role: null, content: ' niet' },
    // { role: null, content: ' verplicht' },
    // { role: null, content: ',' },
    // { role: null, content: ' maar' },
    // { role: null, content: ' kan' },
    // { role: null, content: ' wel' },
    // { role: null, content: ' handig' },
    // { role: null, content: ' zijn' },
    // { role: null, content: '.' },
    // { role: null, content: ' Als' },
    // { role: null, content: ' bewijs' },
    // { role: null, content: 'stuk' },
    // { role: null, content: ' kunt' },
    // { role: null, content: ' u' },
    // { role: null, content: ' relevante' },
    // { role: null, content: ' foto' },
    // { role: null, content: '’s' },
    // { role: null, content: ',' },
    // { role: null, content: ' een' },
    // { role: null, content: ' offerte' },
    // { role: null, content: ',' },
    // { role: null, content: ' een' },
    // { role: null, content: ' fact' },
    // { role: null, content: 'uur' },
    // { role: null, content: ',' },
    // { role: null, content: ' enz' },
    // { role: null, content: 'ovo' },
    // { role: null, content: 'ort' },
    // { role: null, content: ' toevoegen' },
    // { role: null, content: '.' }
  ];

  stream(): Observable<any> {
    return interval(50).pipe(
      take(this.mockData.length),
      map(index => this.mockData[index])
    );
  }
}